///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JIraInteGration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JIraInteGrationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
    [RepositoryFolder("5f7a5679-6a67-4563-8198-51892e1ba010")]
    public partial class JIraInteGrationRepository : RepoGenBaseFolder
    {
        static JIraInteGrationRepository instance = new JIraInteGrationRepository();
        JIraInteGrationRepositoryFolders.GoogleAppFolder _google;

        /// <summary>
        /// Gets the singleton class instance representing the JIraInteGrationRepository element repository.
        /// </summary>
        [RepositoryFolder("5f7a5679-6a67-4563-8198-51892e1ba010")]
        public static JIraInteGrationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JIraInteGrationRepository() 
            : base("JIraInteGrationRepository", "/", null, 0, false, "5f7a5679-6a67-4563-8198-51892e1ba010", ".\\RepositoryImages\\JIraInteGrationRepository5f7a5679.rximgres")
        {
            _google = new JIraInteGrationRepositoryFolders.GoogleAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5f7a5679-6a67-4563-8198-51892e1ba010")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Google folder.
        /// </summary>
        [RepositoryFolder("a4162b9e-f2ac-4154-84f4-cdb93204a89e")]
        public virtual JIraInteGrationRepositoryFolders.GoogleAppFolder Google
        {
            get { return _google; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
    public partial class JIraInteGrationRepositoryFolders
    {
        /// <summary>
        /// The GoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("a4162b9e-f2ac-4154-84f4-cdb93204a89e")]
        public partial class GoogleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lstibInfo;

            /// <summary>
            /// Creates a new Google  folder.
            /// </summary>
            public GoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Google", "/dom[@domain='www.google.co.in']", parentFolder, 30000, null, false, "a4162b9e-f2ac-4154-84f4-cdb93204a89e", "")
            {
                _lstibInfo = new RepoItemInfo(this, "LstIb", ".//input[#'lst-ib']", 30000, null, "3ffee6f3-f1fe-4e64-b958-dfcbdf369dff");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a4162b9e-f2ac-4154-84f4-cdb93204a89e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a4162b9e-f2ac-4154-84f4-cdb93204a89e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LstIb item.
            /// </summary>
            [RepositoryItem("3ffee6f3-f1fe-4e64-b958-dfcbdf369dff")]
            public virtual Ranorex.InputTag LstIb
            {
                get
                {
                    return _lstibInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LstIb item info.
            /// </summary>
            [RepositoryItemInfo("3ffee6f3-f1fe-4e64-b958-dfcbdf369dff")]
            public virtual RepoItemInfo LstIbInfo
            {
                get
                {
                    return _lstibInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}